version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: novelsync_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: novelsync
      MYSQL_USER: novelsync_user
      MYSQL_PASSWORD: novelsync_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database_schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - novelsync_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  # Backend API
  backend:
    build: .
    container_name: novelsync_backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: novelsync_user
      DB_PASSWORD: novelsync_password
      DB_NAME: novelsync
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      PORT: 8080
      GIN_MODE: release
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://localhost:5173
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - novelsync_network
    volumes:
      - uploads_data:/root/uploads

  # Optional: phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: novelsync_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - novelsync_network

volumes:
  mysql_data:
    driver: local
  uploads_data:
    driver: local

networks:
  novelsync_network:
    driver: bridge